//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservacionesTricolor
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CaracteristicaHabitacion
    {
        
        [DisplayName("Características de habitación")]
        public int Id { get; set; }

        [Required]
        [DisplayName("Habitación")]
        public int IdHabitacion { get; set; }

        [Required]
        [DisplayName("Características de habitación")]
        public int IdCaracteristica { get; set; }
    
        public virtual Caracteristica Caracteristica { get; set; }
        public virtual Habitacion Habitacion { get; set; }
    }
}
