//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservacionesTricolor
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Factura
    {
        [DisplayName("Id Factura")]
        public int IdFactura { get; set; }

        [Required]
        [DisplayName("Subtotal")]
        public decimal SubTotal { get; set; }

        [Required]
        [DisplayName("IVA")]
        public decimal IVA { get; set; }

        [Required]
        [DisplayName("Total")]
        public decimal Total { get; set; }

        [Required]
        [DisplayName("Reservación")]
        public int IdReservacion { get; set; }
    
        public virtual Reservacion Reservacion { get; set; }
    }
}
