//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservacionesTricolor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int IdFactura { get; set; }
        public int SubTotal { get; set; }
        public System.DateTime IVA { get; set; }
        public System.DateTime Total { get; set; }
        public int IdReservacion { get; set; }
    
        public virtual Reservacion Reservacion { get; set; }
    }
}
