//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservacionesTricolor
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UsuarioRol
    {
        [DisplayName("Id")]
        public int Id { get; set; }

        [Required]
        [DisplayName("Rol")]
        public int IdRol { get; set; }

        [Required]
        [DisplayName("Usuario")]
        public int IdUsuario { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
